# -*-mode: Makefile;-*-
#

MODULE = AKRL
PACKAGE = TRIPS.AKRL

SRCS = AkrlBundle.java \
	AkrlID.java \
	AkrlIndicator.java \
	AkrlNilTokenException.java \
	AkrlNumber.java \
	AkrlProvenance.java \
	AkrlRole.java \
	AkrlString.java \
	AkrlTerm.java \
	AkrlType.java \
	AkrlValue.java

CLASSES = $(SRCS:.java=.class) 

XTRA =
JFLAGS = -Xlint:unchecked
CONFIGDIR = ../config
include $(CONFIGDIR)/java/lib.mk
