(setf *sample-dialogues* (nconc *sample-dialogues* '(
  ;; Sasaki et al. “Ubiquitination of Ras enhances activation and facilitates binding to select downstream effectors“ (PMC3437993)
  (sasaki-1	; (Introduction)
    "The most frequently mutated oncogenes in the deadliest cancers responsible for human mortality are KRAS, PIK3CA and BRAF. Importantly the signaling enzymes encoded by PIK3CA and BRAF are, in part, regulated by direct binding to activated forms of the Ras proteins suggesting that dysregulation of this key step in signaling is critical for tumor formation. Ras acts as a molecular switch that is activated upon GTP loading and deactivated upon hydrolysis of GTP to GDP. This switch mechanism is common to a wide variety of GTP-binding proteins and is mediated by a conserved structure called the G-domain that consists of five conserved G boxes. Under physiological conditions, the rate of GDP or GTP release from the G-domain is slow. As a consequence the GDP produced by GTP hydrolysis on Ras is trapped and the bulk of cellular Ras accumulates in the GDP-bound ‘off’ state, despite the high GTP/GDP ratio in the cytosol (1–3). Growth factors can turn on Ras by activating Guanine nucleotide Exchange Factors (GEFs) or by inhibiting the GTPase Activating Proteins (GAPs) or by both mechanisms. RasGEFs bind to Ras and lower the transition energy for the nucleotide exchange of the bound GDP for the more abundant cytosolic GTP, whereas RasGAPs bind to Ras and catalyze GTP hydrolysis. The most prevalent oncogenic mutations in Ras (Gly12 and Gly13 in the G1 box, and Gln61 in the G3 box) preserve the GTP bound state by inhibiting intrinsic GTPase activity and by interfering with the ability of GAPs. Other less frequently observed mutations, such as those found in the G4 and G5 boxes, increase the rate of nucleotide exchange, thereby mimicking the GEFs and increasing the GTP-bound state (1–7).")
  (sasaki-2	; (Introduction)
    "Activated Ras controls diverse signaling pathways that ultimately determine Ras-induced cellular responses such as cell proliferation, survival, differentiation and motility. These multiple Ras functions depend on its binding to a range of functionally diverse effector molecules such as Raf, PI3K, AF6 and RASSFs (1). The enhancement of specific effector pathways plays a critical role in maintaining an appropriate biological response (8). The specificity in Ras-induced signaling is primarily determined by the balance between Ras affinity for each of its effectors and the local concentrations of those effectors. In addition, scaffold proteins have been shown to guide activation of specific effector pathway(s). For example, SHOC2/Sur-8 bridges Ras and Raf to specifically enhance the Raf/MEK/ERK pathway without enhancing PI3K/AKT signaling (9, 10).")
  (sasaki-3	; (Results)
    "We utilized an unbiased mass spectrometry-based approach to identify ubiquitination sites of Ras. His-tagged ubiquitin and Flag-tagged K-Ras4B (K-Ras hereafter) were expressed in HEK293T cells at levels similar to endogenous K-Ras (Fig. 1B) and subjected to sequential affinity chromatography. His-ubiquitinated proteins were purified by Co2+ metal affinity chromatography in 8M urea denaturing conditions. His-ubiquitinated K-Ras was subsequently purified with anti-Flag resin. Following purification, mono- and di- ubiquitinated K-Ras appeared to be the major ubiquitination forms, which is consistent with the endogenous K-Ras ubiquitination pattern (Fig. 1, A and B). H-Ras ubiquitination sites were also determined by the same approach. Tandem mass spectrometric analysis of tryptic fragments from the bands migrating at the positions expected for mono- and di-ubiquitinated Ras revealed ubiquitination at Lys residues 104 and 147 of K-Ras, and Lys residues 117, 147 and 170 for H-Ras (fig. S1C). The tryptic peptide with ubiquitination at Lys147 (K147) was the most frequently observed peptide for both K-Ras and H-Ras, while Lys117 appeared as a secondary major ubiquitination site in H-Ras.")
  )))

